services:
  web:
    build: .
    command: sh /usr/src/script/run.sh
    volumes:
      - static:/usr/src/static
      - ./src:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - DEBUG=0
    depends_on:
      - db
  
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static:/usr/src/static
    depends_on:
      - web

volumes:
  postgres_data:
  static:
