# Generated by Django 5.0.6 on 2024-06-20 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_parent_alter_post_text_alter_post_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="favoriters",
            field=models.ManyToManyField(
                related_name="favoriters", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="flaggers",
            field=models.ManyToManyField(
                related_name="flaggers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="voters",
            field=models.ManyToManyField(
                related_name="voters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
